# .readthedocs-pt-br.yaml
# Read the Docs configuration file for Brazilian Portuguese documentation
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build Portuguese documentation by setting the language
# This uses the translations in docs/locale/pt_BR/
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - pip install -e .
    - pip install -r docs/requirements.txt
    - cd docs && sphinx-build -b html -D language=pt_BR . $READTHEDOCS_OUTPUT/html
