name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal code to reproduce the issue
      placeholder: |
        ```python
        from pollywog.core import CalcSet
        # Your code here
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include error messages)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Pollywog Version
      description: Run `python -c "import pollywog; print(pollywog.__version__)"`
      placeholder: "0.2.0"
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python Version
      description: Run `python --version`
      placeholder: "3.12.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Windows 11, macOS 14, Ubuntu 22.04, etc."
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information (screenshots, related issues, etc.)
